### ISSUE TITLE
Debug approve test

### ISSUE THREAD

**Issue by magicalne** [fsy412/nervos_gasless#1]
Hi @fsy412 , I notice you are debugging your test code (I'm not in the discord channel). I can see you just sent a transaction and no receipt was received. So the tx didn't get into the mem-pool. Which means the tx was not valid to godwoken. Something you might miss:

Your paymaster needs to add a stake to the entrypoint contract. And the entrypoint needs to deposit to your paymaster. See the demo in: https://github.com/godwokenrises/account-abstraction/blob/gw-gasless/test/gasless_paymaster.test.ts#L80-L89

You can check the current stake of the entrypoint contract with `entrypoint.paymasterStake()`:
```typescript
    const entryPoint = await ethers.getContractAt('IGaslessEntryPoint', ENTRYPOINT_CONTRACT_ADDRESS)
    const paymasterStake = await entryPoint.paymasterStake()
    console.log(`min stake: ${paymasterStake.toString()}`)
```

There are 3 entities involved in the gasless feature: 
- entrypoint, which maintained by godwoken
- paymaster, which maintained by the dapp developer
- and the user who won't pay for the gas

If you can walk through [gasless demo test](https://github.com/godwokenrises/account-abstraction/blob/gw-gasless/test/gasless_paymaster.test.ts) in your local env, it will help you a lot to understand what's going on about gasless feature.

**Comment by fsy412** [comment]
I've added a stake to the entrypoint contract and deposited to the paymaster.
the 'mint' is wokring , but 'approve' is not working.

I've added the 'mint' case to the mint.ts file, you can check and run.

callData 0x40c10f190000000000000000000000009a4e9c177cca1eedea0e1b86c7b93a67ed60cb5300000000000000000000000000000000000000000000043c33c1937564800000
balance before 30000.0
from 0x9A4E9C177ccA1eeDea0E1b86c7B93a67ed60CB53
tx: https://v1.testnet.gwscan.com/tx/0x0e28ca6b02c9b9d13f315a0968676a0435ea7f73f085e19fb1a8429cd14f173c
balance after 50000.0

**Comment by magicalne** [comment]
I just wanted to let you know that I am still investigating the issue. It may take some time.

**Comment by magicalne** [comment]
I'm so dumb... 

```solidity
    function approve(address spender, uint256 value) external returns (bool) {
        _approve(msg.sender, spender, value);
        return true;
    }
```

The contract uses `msg.sender` in the approve function. And `msg.sender` refers to the address of the call. Guess who is the caller? It's the EntryPoint contract. You can use `tx.origin` maybe, that should fix your problem. Although it's not recommended... Or you can use another way to implement this.

Here is another tip. You can test your contract with hardhat in your local env. The hardhat doesn't support gasless tx natively. But that doesn't matter. If you try to send tx to hardhat network with 0 gas limit, it'll throw some error. You can fix the error  with such [config.](https://github.com/godwokenrises/account-abstraction/blob/gw-gasless/hardhat.config.ts#L90-L95)

**Comment by fsy412** [comment]
Yes, changing tx.sender to tx.origin is dangerous, and may introduce other problems.
The cause of this issue is clear, we can unitize the gasless feature on testnet to easy onboard new user reduce the barrier of entry.
